using System;
using System.Collections.Generic;
using System.Linq;

namespace AutoForm.Generate
{
	internal static partial class Source
	{
		private readonly struct ControlsTemplate
		{
			private ControlsTemplate(IEnumerable<ModelControlPairTemplate> modelControlPairTemplates, IEnumerable<ControlTemplate> controlTemplates)
			{
				_modelControlPairTemplates = modelControlPairTemplates;
				_controlTemplates = controlTemplates;
			}

			private readonly IEnumerable<ModelControlPairTemplate> _modelControlPairTemplates;
			private readonly IEnumerable<ControlTemplate> _controlTemplates;

			private const String TEMPLATE =
@"// <auto-generated/>

#pragma warning disable 1591
namespace AutoForm.Generate
{	
	public static class Controls
	{
#nullable enable
		public static readonly IDictionary<Type, Type> ModelControlMap = new global::System.Collections.ObjectModel.ReadOnlyDictionary<Type, Type>(new Dictionary<Type, Type>()
		{
" + MODEL_CONTROL_PAIRS + @"
		});

" + CONTROLS + @"
#nullable restore
	}
}
#pragma warning restore 1591";


			public ControlsTemplate WithModelControlPairTemplates(IEnumerable<ModelControlPairTemplate> modelControlPairTemplates)
			{
				return new ControlsTemplate(modelControlPairTemplates, _controlTemplates);
			}
			public ControlsTemplate WithControlTemplates(IEnumerable<ControlTemplate> controlTemplates)
			{
				return new ControlsTemplate(_modelControlPairTemplates, controlTemplates);
			}

			public String Build()
			{
				Int32 controlIndex = 0;
				var controls = String.Join("\n\n", _controlTemplates.Select(t => t.Build(ref controlIndex)));
				var modelControlPairs = String.Join(",\n", _modelControlPairTemplates.Select(t => t.Build()));

				return TEMPLATE
					.Replace(MODEL_CONTROL_PAIRS, modelControlPairs)
					.Replace(CONTROLS, controls);
			}

            public override String ToString()
			{
				return Build();
			}
        }
	}

}
