using AutoForm.Analysis.Models;
using System;

namespace AutoForm.Generate.Blazor.Templates
{
	internal sealed partial class SourceFactory
	{
		private readonly struct ErrorTemplate
		{
			private ErrorTemplate(Error error)
			{
				_error = error;
			}

			private readonly Error _error;

			private const String TEMPLATE =
	@"// <auto-generated/>
//" + GENERATED_DATE + @"

//One or more errors have occured during generation of this source. See the information below:

/*
" + ERROR_MESSAGE + @"
*/";

			public ErrorTemplate WithError(Error error)
			{
				return new ErrorTemplate(error);
			}

			public String Build()
			{
				String generatedDate = DateTimeOffset.Now.ToString();
				String errorMessage = String.Join("\n\n", _error.Exceptions);

				return TEMPLATE
					.Replace(GENERATED_DATE, generatedDate)
					.Replace(ERROR_MESSAGE, errorMessage);
			}

			public override String ToString()
			{
				return Build();
			}
		}
	}
}