// <auto-generated/>
#pragma warning disable 1591
namespace AutoForm.Generated
{
	using System;
	using Microsoft.AspNetCore.Components;
	public partial class Component1 : Microsoft.AspNetCore.Components.ComponentBase
	{
#pragma warning disable 1998
		protected override void BuildRenderTree(Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
		{
			__builder.OpenComponent<AutoForm.Generated.GeneratedTestComponent>(0);
			__builder.AddAttribute(1, "Value", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<System.String>(Value));
			__builder.AddAttribute(2, "ValueChanged", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<Microsoft.AspNetCore.Components.EventCallback<System.String>>(Microsoft.AspNetCore.Components.EventCallback.Factory.Create<System.String>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => Value = __value, Value))));
			__builder.CloseComponent();
		}
#pragma warning restore 1998
		[Parameter]
		public String Value { get; set; }
		[Parameter]
		public EventCallback<String> ValueChanged { get; set; }
	}
}
#pragma warning restore 1591