using System;

namespace AutoForm.Generate.Blazor.Templates
{
	internal sealed partial class SourceFactory
	{
		private readonly struct ErrorTemplate
		{
			private ErrorTemplate(String message)
			{
				_message = message;
			}

			private readonly String _message;

			private const String TEMPLATE =
	@"// <auto-generated/>
//" + GENERATED_DATE + @"

//One or more errors have occured during generation of this source. See the information below:

/*
" + ERROR_MESSAGE + @"
*/";

			public ErrorTemplate WithMessage(String message)
			{
				return new ErrorTemplate(message);
			}

			public String Build()
			{
				var generatedDate = DateTimeOffset.Now.ToString();

				return TEMPLATE
					.Replace(GENERATED_DATE, generatedDate)
					.Replace(ERROR_MESSAGE, _message);
			}

			public override String ToString()
			{
				return Build();
			}
		}
	}
}