using System;

namespace AutoForm.Generate
{
	internal static partial class Source
	{
		private readonly struct ErrorTemplate
		{
			private ErrorTemplate(String message)
			{
				_message = message;
			}

			private readonly String _message;

			private const String TEMPLATE =
@"// <auto-generated/>

//One or more errors have occured during generation of this source. See the information below:

/*
" + ERROR_MESSAGE + @"
*/";

			public ErrorTemplate WithMessage(String message)
			{
				return new ErrorTemplate(message);
			}

			public String Build()
			{
				return TEMPLATE
					.Replace(ERROR_MESSAGE, _message);
			}


		}
	}
}
